branches:
  only:
    - master

language: ruby

rvm:
  - "2.3.6"
  - "2.4.3"
  - "2.5.0"

before_install:
  - gem install bundler

addons:
  code_climate:
    repo_token: 2b2b2a8c28682817f985f0afba1e5d643bcc801c6af1a1294869bc118742e95f

after_success:
  - bundle exec codeclimate-test-reporter
